name: AWS CodePipeline Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_codepipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Trigger AWS CodePipeline
      - name: Trigger CodePipeline
        run: |
          PIPELINE_NAME="Lab-Pipeline-Flask"  # Replace with your pipeline name
          aws codepipeline start-pipeline-execution --name $PIPELINE_NAME
          
      # Optional Step 4: Check status of CodePipeline execution
      - name: Check Pipeline Execution Status
        run: |
          PIPELINE_NAME="your-pipeline-name"  # Replace with your pipeline name
          PIPELINE_EXECUTION_ID=$(aws codepipeline list-pipeline-executions --pipeline-name $PIPELINE_NAME --query "pipelineExecutionSummaries[0].pipelineExecutionId" --output text)
          echo "Pipeline execution ID: $PIPELINE_EXECUTION_ID"
          aws codepipeline get-pipeline-execution --pipeline-name $PIPELINE_NAME --pipeline-execution-id $PIPELINE_EXECUTION_ID
